sudo: required
services:
  - docker

before_install:
  - docker build -t tomket/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomket/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-274372526749"
  bucket_path: "docker-react"
  on:
    branch: master